apiVersion: apps/v1
kind: Deployment
metadata:
  name: housepriceapi-deployment
  namespace: customer2
  labels:
    app: housepriceapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housepriceapi
  template:
    metadata:
      labels:
        app: housepriceapi
    spec:
      volumes:
      - name: postcode-storage
        persistentVolumeClaim:
          claimName: postcode-claim
      containers:
      - name: housepricewebapi
        image: localhost:5000/housepricewebapi:1.0.0.10
        volumeMounts:
        - name: postcode-storage
          mountPath: /data/postcodes
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: connectionString
          value: "mongodb://mongodb:27017"
        - name: "POSTCODE_DATA"
          value: "/data/postcodes/ukpostcodes.csv"
