kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: importerwatch-claim
  namespace: customer2
spec:
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi