kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: customer2-data-claim
  namespace: customer2
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi