apiVersion: v1
kind: PersistentVolume
metadata:
  name: customer2-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 5Gi
  hostPath:
      path: /data/mongoData/customer2
