apiVersion: apps/v1
kind: Deployment
metadata:
  name: housepriceweb-deployment
  namespace: customer2
  labels:
    app: houseprice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: houseprice
  template:
    metadata:
      labels:
        app: houseprice
    spec:
      containers:
      - name: housepricesweb
        image: localhost:5000/housepricesweb:1.0.0.6
        env:
        - name: ApiRoot
          value: "http://houseprice-api"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
