apiVersion: v1
kind: PersistentVolume
metadata:
  name: importerprocessing-customer1
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
      storage: 1Gi
  hostPath:
      path: "/host_mnt/c/houseprice/data/customer1/importer/processing"