kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-claim
  namespace: customer1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi