apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: data-claim
      containers:
      - name: mongodb-container
        image: "mongo:3.4-jessie"
        volumeMounts:
        - name: data-storage
          mountPath: /var/lib/mongo
        ports:
        - containerPort: 27017