apiVersion: v1
kind: PersistentVolume
metadata:
  name: postcode
  namespace: customer1
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
      storage: 1Gi
  hostPath:
      path: "c:\postcodes"