apiVersion: v1
kind: PersistentVolume
metadata:
  name: postcode
spec:
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
      storage: 1Gi
  hostPath:
      path: c:\postcode\