kind: Service
apiVersion: v1
metadata:
  name: houseprice-api
  namespace: customer1
  labels:
    app: housepriceapi
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32000
  selector:
    app: housepriceapi