apiVersion: v1
kind: PersistentVolume
metadata:
  name: postcode
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
      storage: 1Gi
  hostPath:
      path: "/host_mnt/c/k8sdemo/data/postcodes"