kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postcode-claim
spec:
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi