kind: Service
apiVersion: v1
metadata:
  name: housepriceweb-service-{clientName}
  labels: 
    partition: {clientName}
spec:
  selector:
    app: houseprice
    partition: {clientName}
  ports:
  - protocol: TCP
    port: 80